package ldr.server.serialization.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: embedding.proto

public final class EmbeddingOuterClass {
  private EmbeddingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmbeddingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Embedding)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>repeated double value = 2;</code>
     * @return A list containing the value.
     */
    java.util.List<java.lang.Double> getValueList();
    /**
     * <code>repeated double value = 2;</code>
     * @return The count of value.
     */
    int getValueCount();
    /**
     * <code>repeated double value = 2;</code>
     * @param index The index of the element to return.
     * @return The value at the given index.
     */
    double getValue(int index);

    /**
     * <code>map&lt;string, string&gt; metas = 3;</code>
     */
    int getMetasCount();
    /**
     * <code>map&lt;string, string&gt; metas = 3;</code>
     */
    boolean containsMetas(
        java.lang.String key);
    /**
     * Use {@link #getMetasMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMetas();
    /**
     * <code>map&lt;string, string&gt; metas = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetasMap();
    /**
     * <code>map&lt;string, string&gt; metas = 3;</code>
     */
    /* nullable */
java.lang.String getMetasOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; metas = 3;</code>
     */
    java.lang.String getMetasOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code Embedding}
   */
  public static final class Embedding extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Embedding)
      EmbeddingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Embedding.newBuilder() to construct.
    private Embedding(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Embedding() {
      value_ = emptyDoubleList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Embedding();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EmbeddingOuterClass.internal_static_Embedding_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMetas();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EmbeddingOuterClass.internal_static_Embedding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EmbeddingOuterClass.Embedding.class, EmbeddingOuterClass.Embedding.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.DoubleList value_ =
        emptyDoubleList();
    /**
     * <code>repeated double value = 2;</code>
     * @return A list containing the value.
     */
    @java.lang.Override
    public java.util.List<java.lang.Double>
        getValueList() {
      return value_;
    }
    /**
     * <code>repeated double value = 2;</code>
     * @return The count of value.
     */
    public int getValueCount() {
      return value_.size();
    }
    /**
     * <code>repeated double value = 2;</code>
     * @param index The index of the element to return.
     * @return The value at the given index.
     */
    public double getValue(int index) {
      return value_.getDouble(index);
    }
    private int valueMemoizedSerializedSize = -1;

    public static final int METAS_FIELD_NUMBER = 3;
    private static final class MetasDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  EmbeddingOuterClass.internal_static_Embedding_MetasEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metas_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMetas() {
      if (metas_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetasDefaultEntryHolder.defaultEntry);
      }
      return metas_;
    }
    public int getMetasCount() {
      return internalGetMetas().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metas = 3;</code>
     */
    @java.lang.Override
    public boolean containsMetas(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetas().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetasMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetas() {
      return getMetasMap();
    }
    /**
     * <code>map&lt;string, string&gt; metas = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetasMap() {
      return internalGetMetas().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metas = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetasOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetas().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metas = 3;</code>
     */
    @java.lang.Override
    public java.lang.String getMetasOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetas().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (getValueList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(valueMemoizedSerializedSize);
      }
      for (int i = 0; i < value_.size(); i++) {
        output.writeDoubleNoTag(value_.getDouble(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMetas(),
          MetasDefaultEntryHolder.defaultEntry,
          3);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      {
        int dataSize = 0;
        dataSize = 8 * getValueList().size();
        size += dataSize;
        if (!getValueList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valueMemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMetas().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        metas__ = MetasDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, metas__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EmbeddingOuterClass.Embedding)) {
        return super.equals(obj);
      }
      EmbeddingOuterClass.Embedding other = (EmbeddingOuterClass.Embedding) obj;

      if (getId()
          != other.getId()) return false;
      if (!getValueList()
          .equals(other.getValueList())) return false;
      if (!internalGetMetas().equals(
          other.internalGetMetas())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      if (getValueCount() > 0) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValueList().hashCode();
      }
      if (!internalGetMetas().getMap().isEmpty()) {
        hash = (37 * hash) + METAS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMetas().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EmbeddingOuterClass.Embedding parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmbeddingOuterClass.Embedding parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmbeddingOuterClass.Embedding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmbeddingOuterClass.Embedding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmbeddingOuterClass.Embedding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EmbeddingOuterClass.Embedding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EmbeddingOuterClass.Embedding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmbeddingOuterClass.Embedding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static EmbeddingOuterClass.Embedding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static EmbeddingOuterClass.Embedding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EmbeddingOuterClass.Embedding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EmbeddingOuterClass.Embedding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EmbeddingOuterClass.Embedding prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Embedding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Embedding)
        EmbeddingOuterClass.EmbeddingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EmbeddingOuterClass.internal_static_Embedding_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMetas();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableMetas();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EmbeddingOuterClass.internal_static_Embedding_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EmbeddingOuterClass.Embedding.class, EmbeddingOuterClass.Embedding.Builder.class);
      }

      // Construct using EmbeddingOuterClass.Embedding.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        value_ = emptyDoubleList();
        internalGetMutableMetas().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EmbeddingOuterClass.internal_static_Embedding_descriptor;
      }

      @java.lang.Override
      public EmbeddingOuterClass.Embedding getDefaultInstanceForType() {
        return EmbeddingOuterClass.Embedding.getDefaultInstance();
      }

      @java.lang.Override
      public EmbeddingOuterClass.Embedding build() {
        EmbeddingOuterClass.Embedding result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EmbeddingOuterClass.Embedding buildPartial() {
        EmbeddingOuterClass.Embedding result = new EmbeddingOuterClass.Embedding(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(EmbeddingOuterClass.Embedding result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          value_.makeImmutable();
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.metas_ = internalGetMetas();
          result.metas_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EmbeddingOuterClass.Embedding) {
          return mergeFrom((EmbeddingOuterClass.Embedding)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EmbeddingOuterClass.Embedding other) {
        if (other == EmbeddingOuterClass.Embedding.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.value_.isEmpty()) {
          if (value_.isEmpty()) {
            value_ = other.value_;
            value_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureValueIsMutable();
            value_.addAll(other.value_);
          }
          onChanged();
        }
        internalGetMutableMetas().mergeFrom(
            other.internalGetMetas());
        bitField0_ |= 0x00000004;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                double v = input.readDouble();
                ensureValueIsMutable();
                value_.addDouble(v);
                break;
              } // case 17
              case 18: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                int alloc = length > 4096 ? 4096 : length;
                ensureValueIsMutable(alloc / 8);
                while (input.getBytesUntilLimit() > 0) {
                  value_.addDouble(input.readDouble());
                }
                input.popLimit(limit);
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                metas__ = input.readMessage(
                    MetasDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableMetas().getMutableMap().put(
                    metas__.getKey(), metas__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.DoubleList value_ = emptyDoubleList();
      private void ensureValueIsMutable() {
        if (!value_.isModifiable()) {
          value_ = makeMutableCopy(value_);
        }
        bitField0_ |= 0x00000002;
      }
      private void ensureValueIsMutable(int capacity) {
        if (!value_.isModifiable()) {
          value_ = makeMutableCopy(value_, capacity);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated double value = 2;</code>
       * @return A list containing the value.
       */
      public java.util.List<java.lang.Double>
          getValueList() {
        value_.makeImmutable();
        return value_;
      }
      /**
       * <code>repeated double value = 2;</code>
       * @return The count of value.
       */
      public int getValueCount() {
        return value_.size();
      }
      /**
       * <code>repeated double value = 2;</code>
       * @param index The index of the element to return.
       * @return The value at the given index.
       */
      public double getValue(int index) {
        return value_.getDouble(index);
      }
      /**
       * <code>repeated double value = 2;</code>
       * @param index The index to set the value at.
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          int index, double value) {

        ensureValueIsMutable();
        value_.setDouble(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double value = 2;</code>
       * @param value The value to add.
       * @return This builder for chaining.
       */
      public Builder addValue(double value) {

        ensureValueIsMutable();
        value_.addDouble(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double value = 2;</code>
       * @param values The value to add.
       * @return This builder for chaining.
       */
      public Builder addAllValue(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureValueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, value_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated double value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = emptyDoubleList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> metas_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMetas() {
        if (metas_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetasDefaultEntryHolder.defaultEntry);
        }
        return metas_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableMetas() {
        if (metas_ == null) {
          metas_ = com.google.protobuf.MapField.newMapField(
              MetasDefaultEntryHolder.defaultEntry);
        }
        if (!metas_.isMutable()) {
          metas_ = metas_.copy();
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return metas_;
      }
      public int getMetasCount() {
        return internalGetMetas().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; metas = 3;</code>
       */
      @java.lang.Override
      public boolean containsMetas(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetMetas().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetasMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMetas() {
        return getMetasMap();
      }
      /**
       * <code>map&lt;string, string&gt; metas = 3;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getMetasMap() {
        return internalGetMetas().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; metas = 3;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getMetasOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetas().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; metas = 3;</code>
       */
      @java.lang.Override
      public java.lang.String getMetasOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMetas().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearMetas() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableMetas().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; metas = 3;</code>
       */
      public Builder removeMetas(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableMetas().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableMetas() {
        bitField0_ |= 0x00000004;
        return internalGetMutableMetas().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; metas = 3;</code>
       */
      public Builder putMetas(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableMetas().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; metas = 3;</code>
       */
      public Builder putAllMetas(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMetas().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Embedding)
    }

    // @@protoc_insertion_point(class_scope:Embedding)
    private static final EmbeddingOuterClass.Embedding DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EmbeddingOuterClass.Embedding();
    }

    public static EmbeddingOuterClass.Embedding getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Embedding>
        PARSER = new com.google.protobuf.AbstractParser<Embedding>() {
      @java.lang.Override
      public Embedding parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Embedding> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Embedding> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EmbeddingOuterClass.Embedding getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Embedding_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Embedding_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Embedding_MetasEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Embedding_MetasEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017embedding.proto\"z\n\tEmbedding\022\n\n\002id\030\001 \001" +
      "(\003\022\r\n\005value\030\002 \003(\001\022$\n\005metas\030\003 \003(\0132\025.Embed" +
      "ding.MetasEntry\032,\n\nMetasEntry\022\013\n\003key\030\001 \001" +
      "(\t\022\r\n\005value\030\002 \001(\t:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Embedding_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Embedding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Embedding_descriptor,
        new java.lang.String[] { "Id", "Value", "Metas", });
    internal_static_Embedding_MetasEntry_descriptor =
      internal_static_Embedding_descriptor.getNestedTypes().get(0);
    internal_static_Embedding_MetasEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Embedding_MetasEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
